version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps", "web"]
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule: { interval: "weekly" }
    labels: ["deps", "desktop"]
